request_api:
  name: Request API
  description: Request API
  target:
    entity:
      integration: catlink
      domain: sensor
  fields:
    api:
      name: API
      description: API path
      example: /token/device/union/list/sorted
      required: true
      selector:
        text:
    params:
      name: Params
      description: Request params
      example: '{"key":"val"}'
      selector:
        object:
    method:
      name: Method
      description: Request method
      default: GET
      example: GET
      selector:
        select:
          options:
            - GET
            - POST
            - POST_GET
    throw:
      name: Throw
      description: Throw result
      default: true
      example: true
      selector:
        boolean:
